# Generated by Django 3.0.3 on 2020-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(max_length=30)),
                ('site_ext', models.CharField(max_length=20)),
                ('site_desc', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('shop', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('model_code', models.CharField(max_length=20, null=True)),
                ('purchase_date', models.DateField(null=True)),
                ('address', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
