# Generated by Django 3.0.3 on 2020-06-27 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrm_id', models.CharField(max_length=10, unique=True)),
                ('agrm_create_date', models.DateField(null=True)),
                ('tenure_month', models.IntegerField()),
                ('eff_date', models.DateField(null=True)),
                ('exp_date', models.DateField(null=True)),
                ('notice_date', models.DateField(null=True)),
                ('notice_period', models.CharField(max_length=2)),
                ('file', models.CharField(max_length=7)),
                ('file_no', models.CharField(max_length=8)),
                ('agrement_advance_amount', models.CharField(max_length=1000000)),
                ('agrement_security_amount', models.CharField(max_length=1000000)),
                ('employee_id', models.CharField(blank=True, max_length=10)),
                ('employee_name', models.CharField(blank=True, max_length=30)),
                ('employee_designation', models.CharField(blank=True, max_length=50)),
                ('employee_phone_number', models.CharField(blank=True, max_length=15)),
                ('employee_email', models.EmailField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('person_type', models.CharField(choices=[('organization', 'organization'), ('person', 'person')], max_length=30)),
                ('type', models.CharField(choices=[('lessee', 'lessee'), ('lessor', 'lessor'), ('witness', 'witness')], max_length=30)),
                ('nid', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=450)),
                ('hasbankinfo', models.CharField(max_length=50)),
                ('sis_supplier_code', models.CharField(blank=True, max_length=50)),
                ('name_of_dealing_person', models.CharField(blank=True, max_length=50)),
                ('phone_number_of_dealing_person', models.CharField(blank=True, max_length=50)),
                ('email_of_dealing_person', models.EmailField(blank=True, max_length=30)),
                ('relationship', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(max_length=30)),
                ('site_ext', models.CharField(blank=True, max_length=20)),
                ('primary_area', models.IntegerField(blank=True, max_length=20)),
                ('secondary_area', models.IntegerField(blank=True, max_length=20)),
                ('tertiary_area', models.IntegerField(blank=True, max_length=20)),
                ('site_desc', models.CharField(max_length=450)),
                ('site_size', models.IntegerField(help_text='size of the site in ft', max_length=100, null=True)),
                ('district', models.CharField(max_length=20)),
                ('site_type', models.CharField(max_length=20)),
                ('last_modified_by', models.CharField(blank=True, max_length=20)),
                ('entry_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Securityline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_line_id', models.CharField(max_length=10)),
                ('from_line_date', models.DateField(null=True)),
                ('to_line_date', models.DateField(null=True)),
                ('total_line_amount', models.IntegerField(null=True)),
                ('agreement_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securityline', to='agreement.Agreement')),
            ],
        ),
        migrations.CreateModel(
            name='Rentline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_rule_no', models.CharField(max_length=10)),
                ('start_period', models.DateField(null=True)),
                ('end_period', models.DateField(null=True)),
                ('rent_per_month', models.CharField(max_length=30, null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('agreement_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentline', to='agreement.Agreement')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=450)),
                ('status', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('property_size', models.IntegerField(help_text='size of the site in ft', max_length=100, null=True)),
                ('district', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('percentage_of_first_owner', models.IntegerField()),
                ('percentage_of_second_owner', models.IntegerField(blank=True, max_length=20, null=True)),
                ('percentage_of_third_owner', models.IntegerField(blank=True, max_length=20, null=True)),
                ('percentage_of_fourth_owner', models.IntegerField(blank=True, max_length=20, null=True)),
                ('percentage_of_fifth_owner', models.IntegerField(blank=True, max_length=20, null=True)),
                ('percentage_of_first_site', models.IntegerField(max_length=20)),
                ('percentage_of_second_site', models.IntegerField(max_length=20, null=True)),
                ('percentage_of_third_site', models.IntegerField(blank=True, max_length=20, null=True)),
                ('percentage_of_fourth_site', models.IntegerField(blank=True, max_length=20, null=True)),
                ('owner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_person', to='agreement.Person')),
                ('owner2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_person', to='agreement.Person')),
                ('owner3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_person', to='agreement.Person')),
                ('owner4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_person', to='agreement.Person')),
                ('owner5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_person', to='agreement.Person')),
                ('site1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_site', to='agreement.Site')),
                ('site2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_site', to='agreement.Site')),
                ('site3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_site', to='agreement.Site')),
                ('site4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_site', to='agreement.Site')),
            ],
        ),
        migrations.AddField(
            model_name='agreement',
            name='main_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreement.Site'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='properties',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agreement.Properties'),
        ),
        migrations.CreateModel(
            name='AdvancePaymentline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_adjustment_rule_no', models.CharField(max_length=10)),
                ('star_period', models.DateField(null=True)),
                ('end_period', models.DateField(null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('advance_adjustment_per_month', models.IntegerField(null=True)),
                ('agreement_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanceline', to='agreement.Agreement')),
            ],
        ),
    ]
