# Generated by Django 3.0.3 on 2020-07-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentline',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='agreement',
            name='total_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentline',
            name='total_months',
            field=models.IntegerField(default=1),
        ),
    ]
