# Generated by Django 3.0.3 on 2020-07-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0002_auto_20200707_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepaymentline',
            name='total_amount',
        ),
    ]
