# Generated by Django 3.0.3 on 2020-03-16 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0003_person_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Properties',
        ),
    ]
