# Generated by Django 3.0.3 on 2020-07-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0003_remove_advancepaymentline_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agrement_advance_amount',
            field=models.IntegerField(),
        ),
    ]
