# Generated by Django 3.0.3 on 2020-03-16 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0004_auto_20200316_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrm_id', models.CharField(max_length=10)),
                ('agrm_create_date', models.DateField(null=True)),
                ('tenure_year', models.IntegerField()),
                ('tenure_month', models.IntegerField()),
                ('eff_date', models.DateField(null=True)),
                ('exp_date', models.DateField(null=True)),
                ('notice_date', models.DateField(null=True)),
                ('notice_period', models.CharField(max_length=2)),
                ('file', models.CharField(max_length=7)),
                ('file_no', models.CharField(max_length=8)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreement.Person')),
            ],
        ),
    ]
