# Generated by Django 3.0.3 on 2020-07-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0004_auto_20200708_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentline',
            name='total_months',
            field=models.IntegerField(),
        ),
    ]
