# Generated by Django 3.0.3 on 2020-07-11 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0005_auto_20200711_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentline',
            name='agreement_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentline', to='agreement.Agreement'),
        ),
    ]
