# Generated by Django 3.0.3 on 2020-05-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0006_rent_rentline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_payment_id', models.CharField(max_length=10)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('agreement_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreement.Agreement')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_id', models.CharField(max_length=10)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('agreement_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreement.Agreement')),
            ],
        ),
        migrations.CreateModel(
            name='Securityline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_line_id', models.CharField(max_length=10)),
                ('from_line_date', models.DateField(null=True)),
                ('to_line_date', models.DateField(null=True)),
                ('total_line_amount', models.IntegerField(null=True)),
                ('security_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreement.Security')),
            ],
        ),
        migrations.CreateModel(
            name='AdvancePaymentline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_payment_line_id', models.CharField(max_length=10)),
                ('from_line_date', models.DateField(null=True)),
                ('to_line_date', models.DateField(null=True)),
                ('total_line_amount', models.IntegerField(null=True)),
                ('advance_payment_line_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreement.AdvancePayment')),
            ],
        ),
    ]
