# Generated by Django 3.0.3 on 2020-07-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0007_auto_20200711_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepaymentline',
            name='agreement_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advanceline', to='agreement.Agreement'),
        ),
    ]
