# Generated by Django 3.0.3 on 2020-05-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0007_advancepayment_advancepaymentline_security_securityline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='agreement_ref',
        ),
        migrations.RemoveField(
            model_name='security',
            name='agreement_ref',
        ),
        migrations.RemoveField(
            model_name='advancepaymentline',
            name='advance_payment_line_ref',
        ),
        migrations.RemoveField(
            model_name='rentline',
            name='rent_ref',
        ),
        migrations.RemoveField(
            model_name='securityline',
            name='security_ref',
        ),
        migrations.AddField(
            model_name='advancepaymentline',
            name='agreement_ref',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='agreement.Agreement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentline',
            name='agreement_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agreement.Agreement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityline',
            name='agreement_ref',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='agreement.Agreement'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdvancePayment',
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
        migrations.DeleteModel(
            name='Security',
        ),
    ]
