# Generated by Django 3.0.3 on 2020-05-10 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0008_auto_20200510_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentline',
            name='agreement_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentline', to='agreement.Agreement'),
        ),
    ]
