# Generated by Django 3.0.3 on 2020-08-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0009_auto_20200818_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentline',
            name='rent_per_month',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
