# Generated by Django 3.0.3 on 2020-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0011_auto_20200819_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_ext',
            new_name='site_extension',
        ),
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('SHOP', 'SHOP'), ('WAREHOUSE', 'WAREHOUSE'), ('SERVICE CENTER', 'SERVICE CENTER'), ('RESIDENT', 'RESIDENT'), ('STORE', 'STORE'), ('OFFICE', 'OFFICE')], max_length=20),
        ),
    ]
