# Generated by Django 3.0.3 on 2020-09-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0012_auto_20200927_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='primary_area',
            new_name='display_area',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_desc',
            new_name='site_description',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='secondary_area',
            new_name='storage_area_inside',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='tertiary_area',
            new_name='storage_area_outside',
        ),
    ]
