# Generated by Django 3.0.3 on 2020-09-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0013_auto_20200927_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='display_area',
            field=models.IntegerField(blank=True, help_text='size of the site in sft', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_size',
            field=models.IntegerField(help_text='size of the site in sft', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='storage_area_inside',
            field=models.IntegerField(blank=True, help_text='size of the site in sft', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='storage_area_outside',
            field=models.IntegerField(blank=True, help_text='size of the site in sft', max_length=20),
        ),
    ]
