# Generated by Django 3.0.3 on 2020-09-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0014_auto_20200927_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='lattitude',
            field=models.DecimalField(decimal_places=4, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=30, null=True),
        ),
    ]
