# Generated by Django 3.0.3 on 2020-09-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0017_auto_20200928_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='file',
        ),
        migrations.AddField(
            model_name='agreement',
            name='serial_no',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreement',
            name='file_no',
            field=models.CharField(max_length=7),
        ),
    ]
