# Generated by Django 3.0.3 on 2020-09-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0018_auto_20200929_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='agrm_create_date',
            new_name='agreement_date',
        ),
    ]
