# Generated by Django 3.0.3 on 2020-09-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0019_auto_20200929_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('lessee', 'lessee'), ('lessor', 'lessor'), ('witness', 'witness')], max_length=30, verbose_name='Lessor type'),
        ),
    ]
