# Generated by Django 3.0.3 on 2020-09-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0020_auto_20200929_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AddField(
            model_name='person',
            name='tin',
            field=models.CharField(default=1, max_length=20, verbose_name='TIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='nid',
            field=models.CharField(blank=True, max_length=20, verbose_name='NID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('Organization', 'Organization'), ('Individual', 'Individual'), ('Others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='sis_supplier_code',
            field=models.CharField(blank=True, default='RNT', max_length=50),
        ),
    ]
