# Generated by Django 3.0.3 on 2020-09-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0021_auto_20200929_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dealing_person_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=10, verbose_name='Is there any dealing person other than lessor?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='postcode',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='thana',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='village',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
