# Generated by Django 3.0.3 on 2020-09-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0023_person_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agreement_cat_type',
            field=models.CharField(choices=[('Relocation', 'Relocation'), ('New', 'New'), ('Renewal', 'Renewal'), ('Extension', 'Extension')], default=1, max_length=30, verbose_name='Agreement category type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='eff_date_ag',
            field=models.DateField(null=True, verbose_name='Effective date as per agreement'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='termination_clause',
            field=models.CharField(choices=[('Both parties agree to uninterrupted tenancy period', 'Both parties agree to uninterrupted tenancy period'), ('Both parties negotiator', 'Both parties negotiator'), ('Both parties  1 month  prior written notice', 'Both parties  1 month  prior written notice'), ('Both parties  2 month  prior written notice', 'Both parties  2 month  prior written notice'), ('Both parties  3 month  prior written notice', 'Both parties  3 month  prior written notice'), ('Both parties  4 month prior written notice', 'Both parties  4 month prior written notice'), ('Both parties  6 month prior written notice', 'Both parties  6 month prior written notice'), ('Lessee  only 1 month prior written notice', 'Lessee  only 1 month prior written notice'), ('Lessee  only 3 month prior written notice', 'Lessee  only 3 month prior written notice'), ('Lessee  only 4 month prior written notice', 'Lessee   only 4 month prior written notice'), ('Lessee  only 6 month prior written notice', 'Lessee  only 6 month prior written notice'), ('Possesion Purchase', 'Possesion Purchase')], default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agrement_advance_amount',
            field=models.DecimalField(decimal_places=4, max_digits=30, null=True, verbose_name='Advance/Prepaid(BDT)'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agrement_security_amount',
            field=models.DecimalField(decimal_places=4, max_digits=30, null=True, verbose_name='Security Deposit(BDT)'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='eff_date',
            field=models.DateField(null=True, verbose_name='Effective date as actual'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='exp_date',
            field=models.DateField(null=True, verbose_name='Expiry date'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='notice_date',
            field=models.DateField(null=True, verbose_name='Notice date'),
        ),
    ]
