# Generated by Django 3.0.3 on 2020-09-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0024_auto_20200929_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='eff_date',
            new_name='effected_date_as_actual',
        ),
        migrations.RenameField(
            model_name='agreement',
            old_name='eff_date_ag',
            new_name='effected_date_as_per_agreement',
        ),
        migrations.RenameField(
            model_name='agreement',
            old_name='exp_date',
            new_name='expiry_date',
        ),
    ]
