# Generated by Django 3.0.3 on 2020-10-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0026_auto_20200929_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='area',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='city',
        ),
        migrations.AddField(
            model_name='properties',
            name='number_of_sites',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='postcode',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='thana',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='village',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='desc',
            field=models.CharField(max_length=450, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='district',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='properties',
            name='division',
            field=models.CharField(max_length=40),
        ),
    ]
