# Generated by Django 3.0.3 on 2020-10-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0027_auto_20201001_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('thana', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=40)),
                ('village', models.CharField(max_length=40)),
            ],
        ),
    ]
