# Generated by Django 3.0.3 on 2020-10-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0028_localarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_extension',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
