# Generated by Django 3.0.3 on 2020-10-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0029_auto_20201005_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='site_description',
        ),
        migrations.AlterField(
            model_name='site',
            name='display_area',
            field=models.IntegerField(blank=True, help_text='size of the site in sft', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='storage_area_inside',
            field=models.IntegerField(blank=True, help_text='size of the site in sft', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='storage_area_outside',
            field=models.IntegerField(blank=True, help_text='size of the site in sft', max_length=20, null=True),
        ),
    ]
