# Generated by Django 3.0.3 on 2020-10-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0030_auto_20201005_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='type',
        ),
        migrations.AlterField(
            model_name='person',
            name='email_of_dealing_person',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_of_dealing_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number_of_dealing_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='relationship',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
