# Generated by Django 3.0.3 on 2020-10-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0031_auto_20201005_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='display_area',
            field=models.IntegerField(blank=True, default=0, help_text='size of the site in sft', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_extension',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
