# Generated by Django 3.0.3 on 2020-10-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0032_auto_20201008_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='desc',
            field=models.CharField(blank=True, max_length=450, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='district',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='division',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='percentage_of_second_site',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='postcode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_size',
            field=models.IntegerField(blank=True, help_text='size of the site in sft', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='thana',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='village',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
