# Generated by Django 3.0.3 on 2020-10-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0033_auto_20201008_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='number_of_owner',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='number_of_sites',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], max_length=20),
        ),
    ]
