# Generated by Django 3.0.3 on 2020-10-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0034_auto_20201008_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='agrement_advance_amount',
            new_name='agreement_advance_amount',
        ),
        migrations.RenameField(
            model_name='agreement',
            old_name='agrement_security_amount',
            new_name='agreement_security_amount',
        ),
    ]
