# Generated by Django 3.0.3 on 2020-10-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0035_auto_20201009_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='tenure_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
