# Generated by Django 3.0.3 on 2020-10-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0036_auto_20201009_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agrm_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
