# Generated by Django 3.0.3 on 2020-10-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0038_auto_20201012_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hasbankinfo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
