# Generated by Django 3.0.3 on 2020-10-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0039_auto_20201012_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='hasbankinfo',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_code',
            field=models.CharField(max_length=4),
        ),
    ]
