# Generated by Django 3.0.3 on 2020-10-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0040_auto_20201013_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='desc',
            field=models.CharField(blank=True, max_length=450, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), (' not active', ' not active')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='type',
            field=models.CharField(blank=True, choices=[('available', 'available'), (' not available', ' not available')], max_length=100, null=True, verbose_name='Availability'),
        ),
    ]
