# Generated by Django 3.0.3 on 2021-02-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0041_auto_20201013_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sis_supplier_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
