# Generated by Django 3.0.3 on 2021-02-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0042_auto_20210215_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sis_supplier_code',
            field=models.CharField(blank=True, default='RNT', max_length=50),
        ),
    ]
