# Generated by Django 3.0.3 on 2021-03-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0043_auto_20210215_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='entry_by',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
