# Generated by Django 3.0.3 on 2021-03-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0045_auto_20210302_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='entry_by',
            field=models.CharField(blank=True, default='admin', max_length=20),
            preserve_default=False,
        ),
    ]
