# Generated by Django 3.0.3 on 2021-03-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0047_remove_site_last_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='entry_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agreement',
            name='entry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='entry_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='entry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='entry_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='properties',
            name='entry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rentline',
            name='entry_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='rentline',
            name='entry_date',
            field=models.DateField(null=True),
        ),
    ]
