# Generated by Django 3.0.3 on 2021-03-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0050_auto_20210304_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sis_supplier_code',
            field=models.SlugField(blank=True, default='A'),
        ),
    ]
