# Generated by Django 3.0.3 on 2021-03-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0053_auto_20210304_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement_cat_type',
            field=models.CharField(choices=[('Relocation', 'Relocation'), ('New', 'New'), ('Renewal', 'Renewal'), ('Extension', 'Extension'), ('Additional Space', 'Additional Space'), ('Amendment Of Lease Agreement -Sep-2019', 'Amendment Of Lease Agreement -Sep-2019'), ('Ground floor', 'Ground floor'), ('Possession purchase', 'Possession purchase'), ('Renewal(Extension)', 'Renewal(Extension)'), ('Space-Extension', 'Space-Extension')], max_length=90, verbose_name='Agreement category type'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='termination_clause',
            field=models.CharField(choices=[('Both parties agree to uninterrupted tenancy period', 'Both parties agree to uninterrupted tenancy period'), ('Both parties Negotiator', 'Both parties Negotiator'), ('Both parties_1 Month prior written notice', 'Both parties_1 Month prior written notice'), ('Both parties_12 Months prior written notice', 'Both parties_12 Months prior written notice'), ('Both parties_3 Months prior written notice', 'Both parties_3 Months prior written notice'), ('Both parties_4 Months prior written notice', 'Both parties_4 Months prior written notice'), ('Both parties_6 Months prior written notice', 'Both parties_6 Months prior written notice'), ('Both parties Negotiator 3 Month notice', 'Both parties Negotiator 3 Month notice'), ('Both parties  4 month prior written notice', 'Both parties  4 month prior written notice'), ('Both parties  6 month prior written notice', 'Both parties  6 month prior written notice'), ('Lessee only_1 Month prior written notice', 'Lessee only_1 Month prior written notice'), ('Lessee only_3 Months prior written notice', 'Lessee only_3 Months prior written notice'), ('Lessee only_4 Months prior written notice', 'Lessee only_4 Months prior written notice'), ('Lessee only_6 Months prior written notice', 'Lessee only_6 Months prior written notice'), ('Possesion Purchase', 'Possesion Purchase')], max_length=70),
        ),
    ]
