# Generated by Django 3.0.3 on 2021-03-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0056_agreement_total_rou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='total_rou',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
