# Generated by Django 3.0.3 on 2021-03-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0057_auto_20210310_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
